---
dependencies: []

galaxy_info:
  author: Olaf Sarnow
  description: Install jitsi meet server on Linux
  license: "license (BSD, MIT)"
  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu
      versions:
        - 18.04
        - 19.10
    - name: CentOS
      version:
        - 7.6
