---
# tasks file for jitsi
# centos version

- name: copy hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  tags: hostname

- hostname:
    name: "{{ ansible_sethostname }}"
  tags: hostname

- name: install pkgs
  yum: name=prosody state=present update_cache=yes
  tags: install

- name: install pkgs
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - git
    - epel-release
    - ca-certificates
    - nginx
    - unzip
    - java-latest-openjdk
    - maven
  tags: install

- name: delete example.conf prodosy
  file:
    path: /etc/prosody/conf.d/example.com.cfg.lua
    state: absent
  tags: prosody

- name: copy prodosy conf
  template:
    src: prosody.conf.j2
    dest: /etc/prosody/conf.d/{{ ansible_setfqdn }}.cfg.lua
  tags: prosody

- name: generate certs prosody
  shell: |
    prosodyctl cert generate {{ ansible_setfqdn }}
    update-ca-trust force-enable
  tags: prosody

- name: link cert
  file:
    src: /var/lib/prosody/{{ ansible_setfqdn }}.crt
    dest: /etc/pki/ca-trust/source/anchors/{{ ansible_setfqdn }}.crt
    state: link
  tags: prosody

- name: update ca
  shell: |
    update-ca-trust extract
  tags: prosody

- name: start prosody
  shell: |
    prosodyctl restart
  tags: prosody

- name: copy nginx conf
  template:
    src: DEFAULT.conf.j2
    dest: /etc/nginx/conf.d/{{ ansible_setfqdn }}.conf
    owner: root
    group: root
    mode: 0644
  tags: nginx

- name: get videobridge
  get_url:
    url: https://download.jitsi.org/jitsi-videobridge/linux/{{ vb_pkg }}.zip
    dest: /var/tmp
  tags: vbridge

- name: unzip videobridge
  unarchive:
    src: /var/tmp/{{ vb_pkg }}.zip
    dest: /var/tmp
    remote_src: yes
  tags: vbridge

- name: copy folder videobridge
  shell: |
    mv  /var/tmp/{{ vb_pkg }} /usr/local/videobridge
  tags: vbridge

- name: create config dir
  file:
    dest: /root/.sip-communicator
    state: directory
  tags: vbridge

- name: configure videobridge
  shell: |
    cat > /root/.sip-communicator/sip-communicator.properties << EOF
    org.jitsi.impl.neomedia.transform.srtp.SRTPCryptoContext.checkReplay=false
    org.jitsi.videobridge.TCP_HARVESTER_PORT=4443
    EOF
  tags: vbridge

- name: start videobridge
  shell:
    cd /usr/local/videobridge ; ./jvb.sh --host=localhost --domain={{ ansible_setfqdn }} --port=5347 --secret=YOURSECRET1 &
  tags: vbridge

- name: Install Jitsi Conference Focus (jicofo)
  git:
    repo: 'https://github.com/jitsi/jicofo.git'
    dest: /usr/local/jicofo
  tags: jicofo

- name: build jicofo
  shell: |
    cd /usr/local/jicofo ; mvn package -DskipTests -Dassembly.skipAssembly=false
    cd /usr/local/jicofo ; unzip target/jicofo-1.1-SNAPSHOT-archive.zip
    cd /usr/local/jicofo/jicofo-1.1-SNAPSHOT-archive ; ./jicofo.sh --host=localhost --domain={{ ansible_setfqdn }}  --secret=YOURSECRET2
  tags: jicofo
