---
# tasks file for jitsi
# ubuntu version

- name: copy hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  tags: hostname

- hostname:
    name: "{{ ansible_sethostname }}"
  tags: hostname

- name: Update all packages to the latest version
  shell: |
    apt update
  tags: install

- name: Update all packages to the latest version
  shell: |
    apt-get -qy -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" upgrade
  tags: install

- name: Install packages
  apt: name={{ item }}
  with_items:
    - openjdk-8-jre-headless
    - nginx
    - debconf-utils
  tags: install

- name: set JAVA_HOME
  shell: |
    echo "JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")" | tee -a /etc/profile
  tags: install

- name: get repo key
  shell: |
    curl -fsSL https://download.jitsi.org/jitsi-key.gpg.key | sudo apt-key add -
  tags: jitsi

- name: set jitsi install options
  shell: |
    echo 'deb https://download.jitsi.org stable/' >> /etc/apt/sources.list.d/jitsi-stable.list
    echo "jitsi-meet-prosody	jitsi-videobridge/jvb-hostname	string {{ ansible_setfqdn }}" | debconf-set-selections
    echo "jitsi-meet-turnserver	jitsi-videobridge/jvb-hostname	string {{ ansible_setfqdn }}" | debconf-set-selections
    echo "jitsi-meet-web-config	jitsi-videobridge/jvb-hostname	string {{ ansible_setfqdn }}" | debconf-set-selections
    echo "jitsi-videobridge2 jitsi-videobridge/jvb-hostname string {{ ansible_setfqdn }}" | debconf-set-selections
    echo "jitsi-meet-turnserver	jitsi-meet-turnserver/jvb-hostname	string {{ ansible_setfqdn }}" | debconf-set-selections

    echo "jitsi-meet-prosody	jitsi-meet-prosody/jvb-hostname string {{ ansible_setfqdn }}" | debconf-set-selections
    echo "jitsi-meet-web-config	jitsi-meet/jvb-hostname	string {{ ansible_setfqdn }}" | debconf-set-selections
    echo "jitsi-meet-web-config	jitsi-meet/cert-choice	select	Generate a new self-signed certificate (You will later get a chance to obtain a Let's encrypt certificate)" | debconf-set-selections
  tags: jitsi-debconf

- name: Update all packages to the latest version
  shell: |
    apt update
  tags: install


- name: Install jitsi
  apt:
    name: jitsi-meet
    state: present
  tags: jitsi

- name: stop nginx
  service:
    name: nginx
    state: stopped
    enabled: true
  tags: nginx


- name: copy acme file
  when: ansible_distribution_version == "18.04"
  template:
    src: install-letsencrypt-cert-1804.sh.j2
    dest: /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh
    owner: root
    group: root
    mode: 0755
  tags: cert

- name: copy acme file
  when: ansible_distribution_version == "19.10"
  template:
    src: install-letsencrypt-cert-1910.sh.j2
    dest: /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh
    owner: root
    group: root
    mode: 0755
  tags: cert


- name: copy nginx conf
  template:
    src: DEFAULT.conf.j2
    dest: /etc/nginx/sites-available/{{ ansible_setfqdn }}.conf
    owner: root
    group: root
    mode: 0644
  tags: nginx

- name: configure cert
  shell: /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh
  tags: cert

- name: Create a symbolic link
  file:
    src: /etc/nginx/sites-available/{{ ansible_setfqdn }}.conf
    dest: /etc/nginx/sites-enabled/{{ ansible_setfqdn }}.conf
    state: link
  tags: nginx

- name: start nginx
  service:
    name: nginx
    state: restarted
  tags: nginx
